# Generated by Django 3.2 on 2021-07-14 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('fashion', 'fashion'), ('vehicles', 'vehicles'), ('others', 'others')], max_length=100)),
                ('period_on_bid', models.DateTimeField(blank=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('uploaded_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.ImageField(upload_to='biduploads')),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
    ]
