# Generated by Django 3.2 on 2021-07-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidproj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidproduct',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bidproduct',
            name='period_on_bid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
